/* Generated by re2c 0.13.5 on Sat Apr  7 23:12:27 2012 */
/* vim: set filetype=cpp: */
/**
 * This is yet another IRC protocol parser.
 * Copyright (C) 2012 Tokuhiro Matsuno.
 *
 * http://tokuhirom.mit-license.org/
 */


#include <string>
#include <vector>
#include <stdlib.h>
#include <string.h>
#include <stdio.h>

#define NANOIRCPARSER_MESSAGE_IS_PARTIAL -2
#define NANOIRCPARSER_PARSE_FAILED -2

class NanoIRCParser {
public:
    struct Message {
        std::string prefix;
        std::string command;
        std::vector<std::string> params;
    };

    /**
    * SEE http://tools.ietf.org/html/rfc1459#page-8 for protocol BNF.
    */
    int parse(
        std::string src,
        Message &msg) {

        char *cursor = (char*)src.c_str();
        char *orig = cursor;
        char *marker = cursor;
        char *mark2 = cursor;
        
    

        /*
        * Note. fix HOST regexp to better one.
        */

    start:
        mark2 = cursor;
    
	{
		char yych;

		yych = (char)*cursor;
		switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':	goto yy6;
		case ':':	goto yy2;
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':	goto yy4;
		default:	goto yy8;
		}
yy2:
		++cursor;
		{
            // ":" prefix SPACE
            goto prefix;
        }
yy4:
		++cursor;
		yych = (char)*cursor;
		goto yy13;
yy5:
		{
            std::string text(mark2, cursor-mark2);
            msg.command = text;
            goto params_space;
        }
yy6:
		yych = (char)*(marker = ++cursor);
		switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':	goto yy9;
		default:	goto yy7;
		}
yy7:
		{
            return return_error(src);
        }
yy8:
		yych = (char)*++cursor;
		goto yy7;
yy9:
		yych = (char)*++cursor;
		switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':	goto yy11;
		default:	goto yy10;
		}
yy10:
		cursor = marker;
		goto yy7;
yy11:
		yych = (char)*++cursor;
		goto yy5;
yy12:
		++cursor;
		yych = (char)*cursor;
yy13:
		switch (yych) {
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':	goto yy12;
		default:	goto yy5;
		}
	}


    prefix:
        // PREFIX = SERVERNAME | NICK ("!" USER)? ("@" HOST)?
        mark2 = cursor;
    
	{
		char yych;
		yych = (char)*cursor;
		switch (yych) {
		case '-':
		case '.':
		case '8':
		case '9':	goto yy20;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':	goto yy19;
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':	goto yy16;
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':	goto yy18;
		default:	goto yy21;
		}
yy16:
		yych = (char)*(marker = ++cursor);
		goto yy38;
yy17:
		{
            std::string text(mark2, cursor-mark2);
            msg.prefix = text;
            goto prefix_space;
        }
yy18:
		yych = (char)*(marker = ++cursor);
		goto yy36;
yy19:
		yych = (char)*++cursor;
		switch (yych) {
		case '.':	goto yy25;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':	goto yy26;
		default:	goto yy24;
		}
yy20:
		yych = (char)*++cursor;
		goto yy24;
yy21:
		++cursor;
		{
            return return_error(src);
        }
yy23:
		++cursor;
		yych = (char)*cursor;
yy24:
		switch (yych) {
		case '-':
		case '.':
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':	goto yy23;
		default:	goto yy17;
		}
yy25:
		yych = (char)*++cursor;
		switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':	goto yy28;
		default:	goto yy24;
		}
yy26:
		++cursor;
		yych = (char)*cursor;
		switch (yych) {
		case '-':
		case '8':
		case '9':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':	goto yy23;
		case '.':	goto yy25;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':	goto yy26;
		default:	goto yy17;
		}
yy28:
		++cursor;
		yych = (char)*cursor;
		switch (yych) {
		case '-':
		case '8':
		case '9':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':	goto yy23;
		case '.':	goto yy30;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':	goto yy28;
		default:	goto yy17;
		}
yy30:
		yych = (char)*++cursor;
		switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':	goto yy31;
		default:	goto yy24;
		}
yy31:
		++cursor;
		yych = (char)*cursor;
		switch (yych) {
		case '-':
		case '8':
		case '9':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':	goto yy23;
		case '.':	goto yy33;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':	goto yy31;
		default:	goto yy17;
		}
yy33:
		++cursor;
		yych = (char)*cursor;
		switch (yych) {
		case '-':
		case '.':
		case '8':
		case '9':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':	goto yy23;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':	goto yy33;
		default:	goto yy17;
		}
yy35:
		marker = ++cursor;
		yych = (char)*cursor;
yy36:
		switch (yych) {
		case '!':	goto yy39;
		case '-':
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':	goto yy35;
		case '.':	goto yy23;
		case '@':	goto yy41;
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '[':
		case '\\':
		case ']':
		case '^':
		case '`':
		case '{':
		case '}':	goto yy37;
		default:	goto yy17;
		}
yy37:
		marker = ++cursor;
		yych = (char)*cursor;
yy38:
		switch (yych) {
		case '!':	goto yy39;
		case '-':
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '[':
		case '\\':
		case ']':
		case '^':
		case '`':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':
		case '{':
		case '}':	goto yy37;
		case '@':	goto yy41;
		default:	goto yy17;
		}
yy39:
		yych = (char)*++cursor;
		switch (yych) {
		case ' ':	goto yy40;
		default:	goto yy54;
		}
yy40:
		cursor = marker;
		goto yy17;
yy41:
		yych = (char)*++cursor;
		switch (yych) {
		case '-':
		case '.':
		case '8':
		case '9':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':	goto yy44;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':	goto yy42;
		default:	goto yy40;
		}
yy42:
		++cursor;
		yych = (char)*cursor;
		switch (yych) {
		case '-':
		case '8':
		case '9':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':	goto yy44;
		case '.':	goto yy46;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':	goto yy42;
		default:	goto yy17;
		}
yy44:
		++cursor;
		yych = (char)*cursor;
yy45:
		switch (yych) {
		case '-':
		case '.':
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':	goto yy44;
		default:	goto yy17;
		}
yy46:
		yych = (char)*++cursor;
		switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':	goto yy47;
		default:	goto yy45;
		}
yy47:
		++cursor;
		yych = (char)*cursor;
		switch (yych) {
		case '-':
		case '8':
		case '9':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':	goto yy44;
		case '.':	goto yy49;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':	goto yy47;
		default:	goto yy17;
		}
yy49:
		yych = (char)*++cursor;
		switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':	goto yy50;
		default:	goto yy45;
		}
yy50:
		++cursor;
		yych = (char)*cursor;
		switch (yych) {
		case '-':
		case '8':
		case '9':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':	goto yy44;
		case '.':	goto yy52;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':	goto yy50;
		default:	goto yy17;
		}
yy52:
		++cursor;
		yych = (char)*cursor;
		switch (yych) {
		case '-':
		case '.':
		case '8':
		case '9':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':	goto yy44;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':	goto yy52;
		default:	goto yy17;
		}
yy54:
		++cursor;
		yych = (char)*cursor;
		switch (yych) {
		case ' ':	goto yy17;
		case '@':	goto yy56;
		default:	goto yy54;
		}
yy56:
		++cursor;
		yych = (char)*cursor;
		switch (yych) {
		case ' ':	goto yy17;
		case '-':
		case '.':
		case '8':
		case '9':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':	goto yy58;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':	goto yy60;
		case '@':	goto yy56;
		default:	goto yy54;
		}
yy58:
		++cursor;
		yych = (char)*cursor;
		switch (yych) {
		case ' ':	goto yy17;
		case '-':
		case '.':
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':	goto yy58;
		case '@':	goto yy56;
		default:	goto yy54;
		}
yy60:
		++cursor;
		yych = (char)*cursor;
		switch (yych) {
		case ' ':	goto yy17;
		case '-':
		case '8':
		case '9':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':	goto yy58;
		case '.':	goto yy62;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':	goto yy60;
		case '@':	goto yy56;
		default:	goto yy54;
		}
yy62:
		++cursor;
		yych = (char)*cursor;
		switch (yych) {
		case ' ':	goto yy17;
		case '-':
		case '.':
		case '8':
		case '9':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':	goto yy58;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':	goto yy63;
		case '@':	goto yy56;
		default:	goto yy54;
		}
yy63:
		++cursor;
		yych = (char)*cursor;
		switch (yych) {
		case ' ':	goto yy17;
		case '-':
		case '8':
		case '9':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':	goto yy58;
		case '.':	goto yy65;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':	goto yy63;
		case '@':	goto yy56;
		default:	goto yy54;
		}
yy65:
		++cursor;
		yych = (char)*cursor;
		switch (yych) {
		case ' ':	goto yy17;
		case '-':
		case '.':
		case '8':
		case '9':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':	goto yy58;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':	goto yy66;
		case '@':	goto yy56;
		default:	goto yy54;
		}
yy66:
		++cursor;
		yych = (char)*cursor;
		switch (yych) {
		case ' ':	goto yy17;
		case '-':
		case '8':
		case '9':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':	goto yy58;
		case '.':	goto yy68;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':	goto yy66;
		case '@':	goto yy56;
		default:	goto yy54;
		}
yy68:
		++cursor;
		yych = (char)*cursor;
		switch (yych) {
		case ' ':	goto yy17;
		case '-':
		case '.':
		case '8':
		case '9':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':	goto yy58;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':	goto yy68;
		case '@':	goto yy56;
		default:	goto yy54;
		}
	}


    prefix_space:
    
	{
		char yych;
		yych = (char)*cursor;
		switch (yych) {
		case ' ':	goto yy72;
		default:	goto yy74;
		}
yy72:
		++cursor;
		yych = (char)*cursor;
		goto yy77;
yy73:
		{
            goto start;
        }
yy74:
		++cursor;
		{
            return return_error(src);
        }
yy76:
		++cursor;
		yych = (char)*cursor;
yy77:
		switch (yych) {
		case ' ':	goto yy76;
		default:	goto yy73;
		}
	}


    params_space:
    
	{
		char yych;
		yych = (char)*cursor;
		switch (yych) {
		case ' ':	goto yy80;
		default:	goto yy82;
		}
yy80:
		++cursor;
		yych = (char)*cursor;
		goto yy85;
yy81:
		{
            goto params;
        }
yy82:
		++cursor;
		{
            return return_error(src);
        }
yy84:
		++cursor;
		yych = (char)*cursor;
yy85:
		switch (yych) {
		case ' ':	goto yy84;
		default:	goto yy81;
		}
	}


    after_params_middle:
    
	{
		char yych;
		yych = (char)*cursor;
		switch (yych) {
		case '\r':	goto yy90;
		case ' ':	goto yy88;
		default:	goto yy92;
		}
yy88:
		++cursor;
		yych = (char)*cursor;
		goto yy96;
yy89:
		{
            goto params;
        }
yy90:
		++cursor;
		switch ((yych = (char)*cursor)) {
		case '\n':	goto yy93;
		default:	goto yy91;
		}
yy91:
		{
            printf("ERROR\n");
            return return_error(src);
        }
yy92:
		yych = (char)*++cursor;
		goto yy91;
yy93:
		++cursor;
		{
            goto success;
        }
yy95:
		++cursor;
		yych = (char)*cursor;
yy96:
		switch (yych) {
		case ' ':	goto yy95;
		default:	goto yy89;
		}
	}


    params:
        // <params>   ::= <SPACE> [ ':' <trailing> | <middle> <params> ]
        mark2 = cursor;
    
	{
		char yych;
		yych = (char)*cursor;
		switch (yych) {
		case ':':	goto yy99;
		default:	goto yy101;
		}
yy99:
		++cursor;
		yych = (char)*cursor;
		goto yy106;
yy100:
		{
            std::string text(mark2+1, cursor-mark2-1);
            msg.params.push_back(text);
            goto crlf;
        }
yy101:
		++cursor;
		yych = (char)*cursor;
		goto yy104;
yy102:
		{
            std::string text(mark2, cursor-mark2);
            msg.params.push_back(text);
            goto after_params_middle;
        }
yy103:
		++cursor;
		yych = (char)*cursor;
yy104:
		switch (yych) {
		case '\n':
		case '\r':
		case ' ':	goto yy102;
		default:	goto yy103;
		}
yy105:
		++cursor;
		yych = (char)*cursor;
yy106:
		switch (yych) {
		case 0x00:
		case '\n':
		case '\r':	goto yy100;
		default:	goto yy105;
		}
	}


    crlf:
        mark2 = cursor;
    
	{
		char yych;
		yych = (char)*cursor;
		switch (yych) {
		case '\r':	goto yy109;
		default:	goto yy111;
		}
yy109:
		++cursor;
		switch ((yych = (char)*cursor)) {
		case '\n':	goto yy112;
		default:	goto yy110;
		}
yy110:
		{
            return return_error(src);
        }
yy111:
		yych = (char)*++cursor;
		goto yy110;
yy112:
		++cursor;
		{
            goto success;
        }
	}

    success:
        return cursor-orig;
    }

    int return_error(const std::string &src) {
        return memchr(src.c_str(), '\015', src.size()) == NULL ? NANOIRCPARSER_MESSAGE_IS_PARTIAL : NANOIRCPARSER_PARSE_FAILED;
    }
};

